version: '2'
services:
  zookeeper:
    image: 1977cbd14810d707fe6faf33c99945d11702804732b63d99f5e5a060308a360c
    ports:
      - "2181:2181"
  kafka:
    image: 2b4d19d1635cbeee8a2b38723cdd263bfd7e84123021060d5e91c7157bbf624e
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
